### ISSUE TITLE
[issue] My module doesn't show up in the repo

### ISSUE THREAD

**Issue by binarynoise** [Xposed-Modules-Repo/submission#169]
I added my module two days ago, but it doesn't show up in the LSPosed App (or the modules json). 
Does it need some kind of verification? Did I mess up the repo? 
I looked into other modules and they have the same file structure.

The bot also automatically builds the website whenever I change something.
Could you have a look at my repo and tell my what I missed?

https://github.com/Xposed-Modules-Repo/de.binarynoise.automaticadvancedsettingsexpander

**Comment by yujincheng08** [comment]
It's shown: https://modules.lsposed.org/module/de.binarynoise.automaticadvancedsettingsexpander

And you should have read: https://github.com/Xposed-Modules-Repo/submission/issues/167#issuecomment-1052561337

**Comment by binarynoise** [comment]
Yeah, sorry for being stupid. I found the missing description just before you answered.

If this happens more often, I'd suggest leaving the submission issue open (to be closed by the submitter or the bot later, when everything is set up) and put a checklist in there (add file x, ..., add GitHub description, add release). Why isn't it in a file like all the other information anyway?
My mind was like: "Issue closed? No need to look at it again"
