### ISSUE TITLE
[appeal] com.crossbowffs.quotelock

### ISSUE THREAD

**Issue by Yubyf** [Xposed-Modules-Repo/submission#189]
The [original repository](https://github.com/apsun/QuoteLock) is no longer maintained and has been archived. I am one of the contributors and have maintained the fork for a long time and have released several new versions and hope to continue releasing future versions here. [Here](https://github.com/Yubyf/QuoteLock) is my repo.

**Comment by yujincheng08** [comment]
I recommend you change the package name because it's confusing that the signature will not match the previous release.

**Comment by Yubyf** [comment]
> I recommend you change the package name because it's confusing that the signature will not match the previous release.

Since changing the package name will result in more user actions on transition, I need to seriously think about it.
