### ISSUE TITLE
[appeal] com.mhook.dialog.fix

### ISSUE THREAD

**Issue by serifer** [Xposed-Modules-Repo/submission#253]
对话框取消修复版

**Comment by serifer** [comment]
The original account is lost and needs to be transferred to this account, how can I prove it?

**Comment by yujincheng08** [comment]
给你个 apk 你签名一下？签名没丢吧

**Comment by serifer** [comment]
> 给你个 apk 你签名一下？签名没丢吧

可以

**Comment by serifer** [comment]
这个是via原版下载地址：https://www.wandoujia.com/apps/6609177 比较小，比较流行  

这个是我签名后的via（去掉后缀zip即可，不用解压）：[via_sign.apk.zip](https://github.com/Xposed-Modules-Repo/submission/files/9276067/via_sign.apk.zip)  

模块仓库发行版地址：https://github.com/Xposed-Modules-Repo/com.mhook.dialog.fix/releases/tag/v1.0.1  

这个是签名获取工具（也是去掉后缀zip即可，不用解压）：[getsign.exe.zip](https://github.com/Xposed-Modules-Repo/submission/files/9276069/getsign.exe.zip)  

以下是签名对比截图  

![image](https://user-images.githubusercontent.com/110091342/183272807-a2bbd126-d575-4e99-9e03-7168d64cbe34.png)  
![image](https://user-images.githubusercontent.com/110091342/183272819-eede68b9-3df5-46a2-b0df-8f07710b6758.png)  

hash是一样的
