### ISSUE TITLE
[issue] XPrivacyLua module outdated

### ISSUE THREAD

**Issue by heinhuiz** [Xposed-Modules-Repo/submission#300]
XPrivacyLua in the repo is still on version 1.32. Please update to the latest version 1.34, which adds Android 13 compatibility.
https://github.com/M66B/XPrivacyLua/releases/
https://bitbucket.org/M66B/xlua-companion/downloads/

**Comment by concenit** [comment]
This is a serious problem: Version 1.32 doesn't work on Android 13, but doesn't warn the user of the risk. This is a particular grave risk for users in countries that are not free, users who rely on XPrivacyLua for protection.
