### ISSUE TITLE
[appeal] eu.faircode.xlua

### ISSUE THREAD

**Issue by M66B** [Xposed-Modules-Repo/submission#301]
As author of XPrivacyLua I want to be able to update the module.

**Comment by yujincheng08** [comment]
Invited.

**Comment by VD171** [comment]
Due to difficulties of communication with the Developers of LSPosed XPrivacyLua is now **unsupported**.
This is a terrible and catastrophic loss.
I pray for understanding.

@canyie
@Dr-TSNG
@Howard20181
@JasonKhew96
@kotori2
@vvb2060
@yujincheng08
