### ISSUE TITLE
[appeal] Hook.JiuWu.Xp

### ISSUE THREAD

**Issue by lovejiuwu** [Xposed-Modules-Repo/submission#391]
不小心拒绝邀请了

**Comment by yujincheng08** [comment]
![image](https://user-images.githubusercontent.com/5022927/235047579-279beab5-36a7-4ad7-9610-1826ebef8df2.png)
我咋不信呢

**Comment by lovejiuwu** [comment]
我好像没有找到

**Comment by yujincheng08** [comment]
没找到啥？在哪里没找到？你这样我们很难帮你。

**Comment by lovejiuwu** [comment]
不太懂 抱歉 我想问 这个提交新xposed模块的流程是怎么样的 非常抱歉

**Comment by yujincheng08** [comment]
发 issue 接受邀请然后管理对应 repo 就行了啊

**Comment by lovejiuwu** [comment]
好的我去看看 谢谢

**Comment by lovejiuwu** [comment]
抱歉 可以详细点嘛

**Comment by yujincheng08** [comment]
https://github.com/Xposed-Modules-Repo/submission/blob/master/README.md

**Comment by lovejiuwu** [comment]
你好还在嘛
