### ISSUE TITLE
[issue] API version Not installed  Xposed API call protection Not installed  Dex Optimizer Wrapper Not installed  Framework version Not installed  Manager version 1.8.6 (6712)  System version 10 (API 29)  Device TECNO MOBILE LIMITED TECNO TECNO LD7   System ABI arm64-v8a

### ISSUE THREAD

**Issue by Fadlrm1** [Xposed-Modules-Repo/submission#416]
API version
Not installed

Xposed API call protection
Not installed

Dex Optimizer Wrapper
Not installed

Framework version
Not installed

Manager version
1.8.6 (6712)

System version
10 (API 29)

Device
TECNO MOBILE LIMITED TECNO TECNO LD7 

System ABI
arm64-v8a

**Comment by Tharuka-Heshan** [comment]
API version
Not installed

Xposed API call protection
Not installed

Dex Optimizer Wrapper
Not installed

Framework version
Not installed

Manager package name
org.lsposed.manager

System version
15 (API 35)

Device
Xiaomi Redmi 23129RAA4G 

System ABI
arm64-v8a
