### ISSUE TITLE
[issue] Meets the requirements but not displayed

### ISSUE THREAD

**Issue by Sohoad** [Xposed-Modules-Repo/submission#518]
Make sure you're not leaving the GitHub repo description blank, which indicates the Xposed module display name.
Make sure you have at least one release.
complied with those requirements but repo didn't appear in more

**Comment by yujincheng08** [comment]
https://modules.lsposed.org/module/xdc.destinyImm 这不是有吗。。。

**Comment by Sohoad** [comment]
> 
ok.谢谢,有延迟吧

**Comment by Sohoad** [comment]
> https://modules.lsposed.org/module/xdc.destinyImm 这不是有吗。。。

ok.谢谢,有延迟吧
