### ISSUE TITLE
[issue] LSPosed Module Repository Not Updating Recent Release

### ISSUE THREAD

**Issue by hujiayucc** [Xposed-Modules-Repo/submission#570]
Greetings,

I've noticed an issue where the LSPosed Module Repository fails to reflect the most recent updates to my module. I've successfully created and uploaded a new Release version to the designated repository (https://github.com/Xposed-Modules-Repo/com.hujiayucc.rpointer), however, despite these updates, the LSPosed repository does not show the changes.

I kindly request your assistance in troubleshooting this problem.

Best Regards,

hujiayucc

**Comment by yujincheng08** [comment]
Have you even thought that it's your issue instead of us?
