### ISSUE TITLE
[appeal] net.lonelytransistor.notificationinsystem

### ISSUE THREAD

**Issue by lonelytransistor** [Xposed-Modules-Repo/submission#624]
Never got the initial invitation

**Comment by yujincheng08** [comment]
![image](https://github.com/Xposed-Modules-Repo/submission/assets/5022927/0350d685-68be-43a2-9726-3a7c25ea7920)
We did invite you.

**Comment by lonelytransistor** [comment]
Strange. Sorry then. Could you resend it please in that case?

**Comment by yujincheng08** [comment]
reinvited.
