### ISSUE TITLE
[issue] Modules missing from list

### ISSUE THREAD

**Issue by dantmnf** [Xposed-Modules-Repo/submission#652]
Affected modules:

* https://github.com/Xposed-Modules-Repo/xyz.cirno.pseudodcdimming
* https://github.com/Xposed-Modules-Repo/xyz.cirno.unfuckzui

**Comment by JasonKhew96** [comment]
![Screenshot_20240310-145243.png](https://github.com/Xposed-Modules-Repo/submission/assets/29531167/56927d74-0c9f-4131-954e-00cf6226e80f)

![Screenshot_20240310-145253.png](https://github.com/Xposed-Modules-Repo/submission/assets/29531167/6723add5-eadd-4fbc-8909-87187ebd265d)

**Comment by JasonKhew96** [comment]
![image](https://github.com/Xposed-Modules-Repo/submission/assets/29531167/ef0d0a37-66a0-4037-89d3-9508760a9d11)
