### ISSUE TITLE
[issue] Module not found

### ISSUE THREAD

**Issue by rifsxd** [Xposed-Modules-Repo/submission#756]
Module io.github.rifsxd.gameunlockerextended is not in the module list, and in modules repo it's getting flagged as "not a module" in GitHub actions

**Comment by JasonKhew96** [comment]
@rifsxd please publish the release after module apk is uploaded OR tag your release properly `{versionName}-{versionCode}`

**Comment by rifsxd** [comment]
I think everything is done correctly

**Comment by rifsxd** [comment]
Anyways it's now on the module list thanks

**Comment by JasonKhew96** [comment]
I it's fixed in https://github.com/Xposed-Modules-Repo/modules/commit/879c3bf16e13ea5ed4237d3e53590b85da498f13

**Comment by rifsxd** [comment]
I get it it's the versioning tag format which is 1-1.0.0 2-1.1.0 and such
