### ISSUE TITLE
[issue] Some module pages do not load

### ISSUE THREAD

**Issue by Howard20181** [Xposed-Modules-Repo/submission#77]
e.g. https://modules.lsposed.org/module/io.github.lamprose.mi_ultra

**Comment by lamprose** [comment]
I also found that.,but it can be seen in the app.Hope  the developer can fix it.

**Comment by satouriko** [comment]
Fixed by https://github.com/Xposed-Modules-Repo/modules/commit/51fdaf71fe74af9f204fbed5f4a3b42851f270b7
