### ISSUE TITLE
[Annoucement] Xposed Module Repository is down

### ISSUE THREAD

**Issue by JasonKhew96** [Xposed-Modules-Repo/submission#811]
The [Xposed Module Repository](https://modules.lsposed.org) is down right now, any repo/module changes will not update the page. We are looking into it, please wait for the further announcement.

**Comment by yujincheng08** [comment]
![image](https://github.com/user-attachments/assets/cfcbd568-ddd8-47b2-a8d9-0d5dd64ff100)
should be fixed

**Comment by JasonKhew96** [comment]
> ![image](https://private-user-images.githubusercontent.com/5022927/395793917-cfcbd568-ddd8-47b2-a8d9-0d5dd64ff100.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTIyNjQsIm5iZiI6MTczNDE5MTk2NCwicGF0aCI6Ii81MDIyOTI3LzM5NTc5MzkxNy1jZmNiZDU2OC1kZGQ4LTQ3YjItYThkOS0wZDVkZDY0ZmYxMDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTRUMTU1OTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGUxY2JhMzEwNzdmZWU3MWYwYTZmMTE3M2E4ZjU2MzFjZGRkNjcxZjZiYTIzMzk5YTQ4ZGM4NTYwNzgzODFiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.SyAZdplp3vZv62v3ZBP4Z2A6JkGAm2csoZqKSvGbLMY) should be fixed

@yujincheng08 
![image](https://github.com/user-attachments/assets/90bf26df-8900-49c0-bc15-bef5520c2624)

**Comment by JasonKhew96** [comment]
oh, nvm

**Comment by yujincheng08** [comment]
since the web has been proxied by cf, the build has also been migrated to cf pages. but for some reasons, the build stuck on waiting for non-existing on-going building. looks like its cf's bug.
